@startuml
left to right direction

Product "1" --- "*" OrderItem
Sale "1" --- "*" OrderItem
Sale "*" --- "1" User

class Product {
    id: Integer
    name: String
    price: Double
}

class Sale {
    id: Integer
    date: Date
}

class OrderItem {
    Id: Integer
    quantidade: Integer
    Double: desconto
}

class User {
    Id: Integer
    email: String
    password: String
    Role: UserRole
}
@enduml